### ISSUE TITLE
Upgrading dependencies

### ISSUE THREAD

**Issue by baldram** [crysknife-io/crysknife#24]
Hi Dmitrii,
I wanted to play around with the Crysknife, but first I tried to upgrade dependencies.
To be honest I'm not good in Maven and also my knowledge regarding the configuration of J2CL related maven plugin is not sufficient. 

I tried to deal with demo's `pom.xml`. Some dependencies can be upgraded easy. The `elemental2` related ones can be bumped from snapshot to `1.0.0` and everything works.
The `com.vertispan.j2cl` related ones could be probably already bumped to `0.4-SNAPSHOT` ([already available in artifactory](https://repo.vertispan.com/j2cl/com/vertispan/j2cl/)).
On the other hand if use the latest `j2cl-maven-plugin` from Vertispan, the above mentioned are probably redundant. Please see this [Colin's PR](https://github.com/Vertispan/connected/commit/6679d7a3d3fb5efd14dcf936db00e4fa4b355f52).

The running goal would probably need to be adjusted to the `watch` approach now. 

I tried to play around with this, but with no luck and I couldn't get it running.
Maybe it's easier for you and switching with dependencies to the latest versions doesn't require very big effort?

PS: Are there coming any breaking changes? The API is Errai like so it should be quite stable.
Then all is about supporting (or not) the features. 
Maybe Crysknife is stable enough for experiment with some Open Source project to let it tested it in action? 

Regards,
Marcin

**Comment by treblereel** [comment]
done

what about API, i ll try to keep it as close as possible to errai api

**Comment by baldram** [comment]
Thanks, I see that it has now even more recent version of dependencies than the one I mentioned in the issue description. So in the demo project `j2cl-maven-plugin` is even the latest `0.11-SNAPSHOT` now. Further, remaining stuff from `com.vertispan.j2cl` is not explicitly included in `pom.xml` but should come as `0.5-SNAPSHOT` automatically. Looks great and should be easy to follow `j2cl-maven-plugin` future releases.

> what about API, i ll try to keep it as close as possible to errai api

I think it's reasonable to follow Errai specification and its well documented API. It's well-designed in general. 
On the other hand small deviations are not a big issue. For instance `@DataElement` instead of `@DataField` since such things can be easy handled with "search and replace" for all project files.
I mentioned above since it's worth to consider using [Elemento](https://github.com/hal/elemento/) which seems to have already Errail like HTML templates ported. Probably no need to duplicate effort. It might be that Crysknife and Elemento complement each other. What's more both come from "one family". I will create a separate issue for this.

> done

I tried to build it locally. I'm not sure what's wrong yet, but I got some error. Earlier I was able to succesfully run some other examples using j2cl-maven-plugin from Vertispan.

The step regarding installing the `crysknife` locally was successfull. Further I tried to build the demo.
Then `mvn clean install` or `mvn clean j2cl:watch` leads to following.
(I also tried to switch from JDK13 to JDK8 - didn't help). Maybe I will need to clean up a little `.m2` folder manually.

```bash
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:05 min
[INFO] Finished at: 2019-11-23T20:28:30+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vertispan.j2cl:j2cl-maven-plugin:0.11-SNAPSHOT:build (build-js) on project demo: Execution build-js of goal com.vertispan.j2cl:j2cl-maven-plugin:0.11-SNAPSHOT:build failed: java.nio.file.FileSystemNotFoundException: /home/msx/.m2/repository/xerces/xerces-impl/2.6.2/xerces-impl-2.6.2.jar -> [Help 1]
[ERROR] 
```
I guess demo builds fine for you?

**Comment by baldram** [comment]
It is still unsuccessful. Does the demo build and run fine for you? 
I did the following steps.

1. Deleted and freshly cloned the Crysknife project. 
2. Deleted from `.m2` everything under: `com.vertispan`, `org.gwtproject`, `org.realityforge` (the last one since there is, maybe indirect, dependency to `/org/realityforge/com/google/jsinterop/base/1.0.0-b2-e6d791f`).
3. Successfully installed Crysknife with `mvn clean install`.
4. Within a `/demo` folder I tried to compile the demo app. 
5. I got `BUILD FAILURE` as following (only unsuccessful parts of the full log below).
Some `xerces-impl-2.6.2.jar` related issue. 

```shell
Removing dependency javax.validation:validation-api:jar:1.0.0.GA:compile, no replacement
Removing dependency org.realityforge.com.google.jsinterop:base:jar:1.0.0-b2-e6d791f:compile, replacing with com.vertispan.jsinterop:base:jar:1.0.0-SNAPSHOT
done with pool work for com.google.code.findbugs:jsr305:3.0.2 Hash in 103ms
done with pool work for com.google.code.findbugs:jsr305:3.0.1 Hash in 105ms
java.nio.file.FileSystemNotFoundException: /home/msx/.m2/repository/xerces/xerces-impl/2.6.2/xerces-impl-2.6.2.jar
        at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:120)
        at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:117)
        at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
        at java.nio.file.FileSystems.newFileSystem(FileSystems.java:276)
        at net.cardosi.mojo.cache.CachedProject.lambda$hash$34(CachedProject.java:711)
        at net.cardosi.mojo.cache.CachedProject.lambda$null$7(CachedProject.java:313)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577done with pool work for a)
        at java.util.concurrent.CompletableFuture$Completion.run(Crogs4mj:pletableFuture.java:442)
        aatrgs4j:2.0.26 Hash in 147ms
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
done with pool work for xerces:xerces-impl:2.6.2 Hash in 17ms
done with pool work for com.google.errorprone:error_prone_annotations:2.0.18 Hash in 16ms
done with pool work for com.google.javascript:closure-compiler-externs:v20160713 Hash in 7ms
java.nio.file.FileSystemNotFoundException: /home/msx/.m2/repository/xml-apis/xml-apis/2.6.2/xml-apis-2.6.2.jar
        at com.sun.nio.zipfs.ZipFileSystem.<initdone with pool work for com.google.errorprone:error_prone_annotations:2.0.12 Hash in 3ms
>(ZipFileSystem.java:120)
        at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:117)
        at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
        at java.nio.file.FileSystems.newFileSystem(FileSystems.java:276)
        at net.cardosi.mojo.cache.CachedProject.lambda$hash$34(CachedProject.java:711)
        at net.cardosi.mojo.cache.Cachedone wdProject.lambda$null$7(CachedProject.java:313)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
ith pool work for com.google.code.gson:gson:2.7 Hash in 48ms
done with pool work for xml-apis:xml-apis:2.6.2 Hash in 20ms
done with pool work for com.vertispan.j2cl:gwt-internal-annotations:0.4-SNAPSHOT Hash in 1ms
```
...and finally:
```bash
done with pool work for junit:junit:3.8.1 Hash in 23ms
done with pool work for org.checkerframework:checker-qual:2.8.1 Hash in 26ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:38 min
[INFO] Finished at: 2019-11-23T21:08:23+01:00
[INFO] ------------------------------------------------------------------------
done with pool work for commons-io:commons-io:2.6 Hash in 15ms
done with pool work for commons-codec:commons-codec:1.11 Hash in 31ms
done with pool work for org.codehaus.mojo:animal-sniffer-annotations:1.18 Hash in 1ms
[ERROR] Failed to execute goal com.vertispan.j2cl:j2cl-maven-plugin:0.11-SNAPSHOT:build (build-js) on project demo: Execution build-js of goal com.vertispan.j2cl:j2cl-maven-plugin:0.11-SNAPSHOT:build failed: java.nio.file.FileSystemNotFoundException: /home/msx/.m2/repository/xerces/xerces-impl/2.6.2/xerces-impl-2.6.2.jar -> [Help 1]
done with pool work for org.gwtproject.callback:gwt-callback:HEAD-20180601.153013-1 Hash in 1ms
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
done with pool work for org.gwtproject.event:gwt-event:HEAD-20180603.190905-2 Hash in 1ms
done with pool work for org.gwtproject.event:gwt-event:HEAD-20180529.114207-4 Hash in 3ms
done with pool work for org.gwtproject.dom:gwt-dom-style-definitions:1.0-SNAPSHOT Hash in 53ms
```
Would you please advise? Do you have any idea?

**Comment by baldram** [comment]
Ok. After using the most recent j2cl-maven-plugin snapshot from Nov 25 it worked!
More details here:
https://gitter.im/vertispan/j2cl?at=5ddbf71ad2c92c2275f45002

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```
So, everything is fine! Thanks!
Shall we close the issue @treblereel ?
